<?php
/**
 * @author Barwenock
 * @copyright Copyright (c) Barwenock
 * @package Social Authorizes for Magento 2
 */

/**
 * @var $block \Barwenock\SocialAuth\Block\SocialAuth\Socials
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<?php if ($block->displaySocialsOn()): ?>
<div class="socialauth_container">
    <?php if (!$block->ifCustomerLogin() && $block->isAnySocialEnabled()): ?>
        <div class="socialauth_title">
            <h3>
                <?= $escaper->escapeHtml(__("Login With Social Media")) ?>
            </h3>
        </div>
        <div class="social_block">
            <?php if ($block->configHelper->getFacebookStatus() == 1): ?>
                <div  id="fblogin" class="fblogin socialauth fb_button_ps">
                    <img src="<?= $escaper->escapeUrl($block->getSocialConnectImage('facebook'))?>"
                         alt="<?= $escaper->escapeHtml(__('Facebook'))?>"
                         title="<?= $escaper->escapeHtml(__('Connect with Facebook'))?>"/>
                </div>
            <?php endif ?>

            <?php if ($block->configHelper->getTwitterStatus() == 1): ?>
                <div  id="twitter" class="twitter socialauth">
                    <img src="<?= $escaper->escapeUrl($block->getSocialConnectImage('twitter'))?>"
                         alt="<?= $escaper->escapeHtml(__('Twitter'))?>"
                         title="<?= $escaper->escapeHtml(__('Connect with Twitter'))?>" />
                </div>
            <?php endif; ?>

            <?php if ($block->configHelper->getGoogleStatus() == 1): ?>
                <div id="google" class="google socialauth">
                    <img src="<?= $escaper->escapeUrl($block->getSocialConnectImage('google'))?>"
                         alt="<?= $escaper->escapeHtml(__('Google')) ?>"
                         title="<?= $escaper->escapeHtml(__('Connect with Google')) ?>">
                </div>
            <?php endif; ?>

            <?php if ($block->configHelper->getLinkedinStatus() == 1): ?>
                <div  id="linkedin" class="linkedin socialauth">
                    <img src="<?= $escaper->escapeUrl($block->getSocialConnectImage('linkedin'))?>"
                         alt="<?= $escaper->escapeHtml(__('LinkedIn'))?>"
                         title="<?= $escaper->escapeHtml(__('Connect with LinkedIn'))?>" />
                </div>
            <?php endif; ?>

            <?php if ($block->configHelper->getInstagramStatus() == 1): ?>
                <div  id="instagram" class="instagram socialauth">
                    <img src="<?= $escaper->escapeUrl($block->getSocialConnectImage('instagram'))?>"
                         alt="<?= $escaper->escapeHtml(__('Instagram'))?>"
                         title="<?= $escaper->escapeHtml(__('Connect with Instagram'))?>" />
                </div>
            <?php endif; ?>
        </div>
    <?php endif ?>
</div>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "*":{
            "fbBlockPlugin":<?= /* @noEscape */ $block->getFacebookBlockData(); ?>,
            "socialLoginPopup":<?= /* @noEscape */ $block->getPopupData(); ?>
    }
}
</script>
