<?php
/**
 * @var $block \Barwenock\SocialAuth\Block\Product\ProductShare
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<?php if ($block->productShareStatus() == 1) : ?>
<?php
    $product = $block->getCurrentProduct();
    $productName = urlencode($product->getName());
    $productUrl = urlencode($product->getProductUrl());
    $_sty = "width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes";
?>
    <div class="wk-social-media-icons">
        <a href="<?=
        $escaper->escapeUrl("https://www.facebook.com/sharer/sharer.php?u=" . $productUrl . "&t=" . $productName);
        ?>"
           onclick='javascript:window.open(this.href, "" ,"<?= $block->escapeHtml($_sty); ?>"); return false'
           title="Share Facebook">
            <img src="<?=
            $escaper->escapeUrl($block->getViewFileUrl('Barwenock_SocialAuth::images/facebook.png'));
            ?>"
                 alt="Facebook" width="40px" height="40px">
        </a>

        <a href="<?=
        $escaper->escapeUrl("https://twitter.com/intent/tweet?url=" . $productUrl . $productName);
        ?>"
           onclick='javascript:window.open(this.href, "" ,"<?= $block->escapeHtml($_sty); ?>"); return false'
           title="Share Twitter">
            <img src="<?=
            $escaper->escapeUrl($block->getViewFileUrl('Barwenock_SocialAuth::images/twitter.png'));
            ?>"
                 alt="Twitter" width="40px" height="40px">
        </a>

        <a href="<?= $escaper->escapeUrl("https://www.linkedin.com/share?url=" . $productUrl); ?>"
           onclick='javascript:window.open(this.href, "", "<?= $block->escapeHtml($_sty); ?>"); return false'
           title="Share LinkedIn">
            <img src="<?= $escaper->escapeUrl(
                $block->getViewFileUrl('Barwenock_SocialAuth::images/linkedin.png')
            ); ?>"
                 alt="LinkedIn" width="40px" height="40px">
        </a>
    </div>
<?php endif; ?>

