<?php
/**
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<div id="authenticationPopup" data-bind="scope:'authenticationPopup'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#authenticationPopup": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        },
        "*": {
            "Magento_Ui/js/block-loader":
                "<?= $escaper->escapeJs($block->getViewFileUrl('images/loader-1.gif')) ?>"
            },
            "*": {
             "Barwenock_SocialAuth/js/authentication-popup": {
                   "serializedConfig": <?= $block->getSerializedConfig() ?>,
                   "socialsConfiguration":<?= $block->getData('socialAuthHelper')->serializeData(
                       $block->getData('socialAuthHelper')->getSocialsConfiguration()
                    ) ?>
                }
            }
        }
    </script>
</div>
